CREATE SEQUENCE GENERATOR START WITH 8
INCREMENT BY 1
MAXVALUE 100000
NOCYCLE
NOCACHE;

DROP SEQUENCE GENERATOR;

DROP TABLE ADRESA;

CREATE TABLE ABONAMENT
(TIP VARCHAR(20) PRIMARY KEY, PRET NUMBER(10), DATA_INCEPUT DATE, DATA_SFARSIT DATE);

INSERT INTO ABONAMENT VALUES
('NELIMITAT',200,SYSDATE,SYSDATE);

INSERT INTO ABONAMENT VALUES
('12 SEDINTE',180,SYSDATE,SYSDATE);

INSERT INTO ABONAMENT VALUES
('8 SEDINTE',150,SYSDATE,SYSDATE);

INSERT INTO ABONAMENT VALUES
('4 SEDINTE',120,SYSDATE,SYSDATE);

INSERT INTO ABONAMENT VALUES
('O SEDINTA',40,SYSDATE,SYSDATE);

SELECT * FROM ABONAMENT;

CREATE TABLE ADRESA (ID_ADRESA NUMBER(10) PRIMARY KEY, 
NUME_STRADA VARCHAR(20), NR_STRADA NUMBER(10), SECTOR NUMBER(10));

INSERT INTO ADRESA VALUES
(GENERATOR.NEXTVAL,'BD. UNIRII',11,3);

INSERT INTO ADRESA VALUES
(GENERATOR.NEXTVAL,'ALEEA TANDAREI',18,3);

INSERT INTO ADRESA VALUES
(GENERATOR.NEXTVAL,'STRADA ISTRIEI',20,3);

INSERT INTO ADRESA VALUES
(GENERATOR.NEXTVAL,'STRADA LUMINITA',1,6);

INSERT INTO ADRESA VALUES
(GENERATOR.NEXTVAL,'STRADA SATELITULUI',71,1);

SELECT * FROM ADRESA;

CREATE SEQUENCE GENERATOR START WITH 1001
INCREMENT BY 1
MAXVALUE 100000
NOCYCLE
NOCACHE;

CREATE TABLE SEDIU 
(ID_SEDIU NUMBER(10) PRIMARY KEY, NR_SALI NUMBER(10) NOT NULL);

INSERT INTO SEDIU VALUES
(GENERATOR.NEXTVAL,10);

INSERT INTO SEDIU VALUES
(GENERATOR.NEXTVAL,5);

INSERT INTO SEDIU VALUES
(GENERATOR.NEXTVAL,1);
INSERT INTO SEDIU VALUES
(GENERATOR.NEXTVAL,3);
INSERT INTO SEDIU VALUES
(GENERATOR.NEXTVAL,7);
INSERT INTO SEDIU VALUES
(GENERATOR.NEXTVAL,4);

SELECT * FROM SEDIU;

CREATE TABLE STIL_DE_DANS 
(ID_STIL NUMBER(10) PRIMARY KEY, DENUMIRE VARCHAR(20));

INSERT INTO STIL_DE_DANS VALUES
(GENERATOR.NEXTVAL, 'DANCEHALL');

INSERT INTO STIL_DE_DANS VALUES
(GENERATOR.NEXTVAL, 'HIP HOP');

INSERT INTO STIL_DE_DANS VALUES
(GENERATOR.NEXTVAL, 'LOCKING');

INSERT INTO STIL_DE_DANS VALUES
(GENERATOR.NEXTVAL, 'HOUSE');

INSERT INTO STIL_DE_DANS VALUES
(GENERATOR.NEXTVAL, 'WAACKING');

INSERT INTO STIL_DE_DANS VALUES
(GENERATOR.NEXTVAL, 'VOGUE');

SELECT * FROM STIL_DE_DANS;

CREATE TABLE SALA 
(ID_SALA NUMBER(10) PRIMARY KEY, ID_SEDIU NUMBER(10) REFERENCES SEDIU(ID_SEDIU));

INSERT INTO SALA VALUES
(GENERATOR.NEXTVAL, 3);

INSERT INTO SALA VALUES
(GENERATOR.NEXTVAL, 1);

INSERT INTO SALA VALUES
(GENERATOR.NEXTVAL, 1);

INSERT INTO SALA VALUES
(GENERATOR.NEXTVAL, 1);

INSERT INTO SALA VALUES
(GENERATOR.NEXTVAL, 1);

INSERT INTO SALA VALUES
(GENERATOR.NEXTVAL, 1);

INSERT INTO SALA VALUES
(GENERATOR.NEXTVAL, 2);

INSERT INTO SALA VALUES
(GENERATOR.NEXTVAL, 2);

INSERT INTO SALA VALUES
(GENERATOR.NEXTVAL, 2);

INSERT INTO SALA VALUES
(GENERATOR.NEXTVAL, 4);

SELECT * FROM SALA;

CREATE TABLE CLASA (ID_CLASA NUMBER(10) PRIMARY KEY,
ID_STIL NUMBER(10) REFERENCES STIL_DE_DANS(ID_STIL), 
ID_SALA NUMBER(10) REFERENCES SALA(ID_SALA));

INSERT INTO CLASA VALUES
(GENERATOR.NEXTVAL, 1,100);

INSERT INTO CLASA VALUES
(GENERATOR.NEXTVAL, 1,200);

INSERT INTO CLASA VALUES
(GENERATOR.NEXTVAL, 1,300);

INSERT INTO CLASA VALUES
(GENERATOR.NEXTVAL, 2,400);

INSERT INTO CLASA VALUES
(GENERATOR.NEXTVAL, 2,500);

INSERT INTO CLASA VALUES
(GENERATOR.NEXTVAL, 3,600);

INSERT INTO CLASA VALUES
(GENERATOR.NEXTVAL, 4,700);

INSERT INTO CLASA VALUES
(GENERATOR.NEXTVAL, 4,800);

INSERT INTO CLASA VALUES
(GENERATOR.NEXTVAL, 1,900);

SELECT * FROM CLASA;

CREATE TABLE CURSANT
(ID_CURSANT NUMBER(10)PRIMARY KEY,NUME VARCHAR(20) NOT NULL,
PRENUME VARCHAR(20) NOT NULL,DATA_NASTERII DATE,
EMAIL VARCHAR(20),
ID_CLASA NUMBER(10) REFERENCES CLASA(ID_CLASA));

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'POPESCU','MIHAELA',SYSDATE,NULL,10);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'GEORGESCU','IOANA',SYSDATE,'IOANA@GMAIL.COM'10);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'RUS','ALEXANDRU',SYSDATE,NULL,10);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'MECHIE','DARIA',SYSDATE,'JMECHIE@GMAIL.COM',10);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'TRANDAFIR','PATRICIA',SYSDATE,'BLUEPATY@POLI.COM',20);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'DUMITRU','MARIA',SYSDATE,'ESCALIBUR@CRAZY.COM',20);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'BONDOC','ANA',SYSDATE,NULL,20);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'OPREA','GEORGE',SYSDATE,NULL,30);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'TUDORACHE','MIRUNA',SYSDATE,NULL,30);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'PARASCHIV','STEFAN',SYSDATE,NULL,30);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'IVANCIUC','GHEORGHE',SYSDATE,NULL,30);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'DICULESCU','LUCA',SYSDATE,NULL,30);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'DOGARU','DIANA',SYSDATE,NULL,30);

INSERT INTO CURSANT VALUES
(GENERATOR.NEXTVAL, 'ANCU','LORETA',SYSDATE,NULL,30);


SELECT * FROM CURSANT;

CREATE TABLE EVENIMENT 
(ID_EVENIMENT NUMBER(10) PRIMARY KEY, DATA DATE , NRPUNCTE1 NUMBER(10),
NRPUNCTE2 NUMBER(10), NRPUNCTE3 NUMBER(10), NRPUNCTEPARTICIPARE NUMBER(10),
ID_SEDIU NUMBER(10) REFERENCES SEDIU(ID_SEDIU));

INSERT INTO EVENIMENT VALUES
(GENERATOR.NEXTVAL,SYSDATE, 20,15,10,5,3);

INSERT INTO EVENIMENT VALUES
(GENERATOR.NEXTVAL,SYSDATE, 30,10,5,0,1);

INSERT INTO EVENIMENT VALUES
(GENERATOR.NEXTVAL,SYSDATE, 50,25,10,5,2);

INSERT INTO EVENIMENT VALUES
(GENERATOR.NEXTVAL,SYSDATE, 20,10,5,0,4);

INSERT INTO EVENIMENT VALUES
(GENERATOR.NEXTVAL,SYSDATE, 25,15,7,3,2);

SELECT * FROM EVENIMENT;

DROP TABLE INCASARI;
CREATE TABLE INCASARI(ID_INCASARI NUMBER(20) PRIMARY KEY,
SUMA NUMBER(20), LUNA VARCHAR(20), 
ID_SEDIU NUMBER(10) REFERENCES SEDIU(ID_SEDIU));

INSERT INTO INCASARI VALUES
(GENERATOR.NEXTVAL, 10000, 'SEPTEMBER', 1);

INSERT INTO INCASARI VALUES
(GENERATOR.NEXTVAL, 9550, 'OCTOBER', 1);

INSERT INTO INCASARI VALUES
(GENERATOR.NEXTVAL, 9000, 'NOVEMBER', 1);

INSERT INTO INCASARI VALUES
(GENERATOR.NEXTVAL, 5000, 'DECEMBER', 1);

INSERT INTO INCASARI VALUES
(GENERATOR.NEXTVAL, 12000, 'JANUARY', 1);

INSERT INTO INCASARI VALUES
(GENERATOR.NEXTVAL, 7000, 'FEBRUARY', 1);

SELECT * FROM INCASARI;

DROP TABLE ANGAJAT;

CREATE TABLE ANGAJAT
(ID_SALARIAT NUMBER(10) PRIMARY KEY, NUME VARCHAR(20) NOT NULL,
PRENUME VARCHAR(20) NOT NULL , TELEFON VARCHAR(20));

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'GEORGE', 'MIHAI', '07232183');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'POPA', 'IOANA', '07273722');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'LUCULET', 'DORINA', '071112183');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'VASILE', 'CRISTIAN', '07232555');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'PARLOG', 'FILIP', '07236783');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'TANASE', 'DANIEL', '07192183');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'DUNCA', 'IOANA', '071976323');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'RADULESCU', 'DENISA', '07197773');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'OPREA', 'TUDOR', '07144483');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'RUS', 'ION', '07144483');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'MARIA', 'ANA', '07144483');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'IONESCU', 'OANA', '075678911');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'GHEORGHE', 'ALEXANDRA', '073456113');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'PAUN', 'DARIA', '071223383');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'TOMA', 'MARIUS', '07987653');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'FLORINACHE', 'MATEI', '071122093');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'POP', 'PAUL', '076767673');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'MADGEARU', 'RADU', '07213412873');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'ION', 'RALUCA', '07144483');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'IGNAT', 'SIMION', '07144483');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'CONDRATOV', 'COSMIN', '07144483');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'MACOVEI', 'ANA', '07144483');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'LAUR', 'VASILE', '07144483');

INSERT INTO ANGAJAT VALUES
(GENERATOR.NEXTVAL, 'ivan', 'corina', '07654483');
SELECT * FROM ANGAJAT;

DROP TABLE INSTRUCTOR;
CREATE TABLE INSTRUCTOR 
(ID_SALARIAT NUMBER(10) REFERENCES ANGAJAT(ID_SALARIAT) PRIMARY KEY,
ID_STIL NUMBER(10) REFERENCES STIL_DE_DANS(ID_STIL));

INSERT INTO INSTRUCTOR VALUES (5760,1);
INSERT INTO INSTRUCTOR VALUES (5457,2);
INSERT INTO INSTRUCTOR VALUES (6063,3);
INSERT INTO INSTRUCTOR VALUES (6366,4);
INSERT INTO INSTRUCTOR VALUES (105,6);
INSERT INTO INSTRUCTOR VALUES (106,5);

SELECT * FROM INSTRUCTOR;

CREATE TABLE RECEPTIONIST(ID_SALARIAT NUMBER(10) REFERENCES ANGAJAT(ID_SALARIAT) PRIMARY KEY,
ID_SEDIU NUMBER(10) REFERENCES SEDIU(ID_SEDIU));

INSERT INTO RECEPTIONIST VALUES(6669,3);
INSERT INTO RECEPTIONIST VALUES(6972,1);
INSERT INTO RECEPTIONIST VALUES(100,2);
INSERT INTO RECEPTIONIST VALUES(107,4);
INSERT INTO RECEPTIONIST VALUES(108,6);


SELECT * FROM RECEPTIONIST;

CREATE TABLE PAZNIC(ID_SALARIAT NUMBER(10) REFERENCES ANGAJAT(ID_SALARIAT),
ID_SEDIU NUMBER(10) REFERENCES SEDIU(ID_SEDIU));

INSERT INTO PAZNIC VALUES(101,1);
INSERT INTO PAZNIC VALUES(102,2);
INSERT INTO PAZNIC VALUES(109,4);
INSERT INTO PAZNIC VALUES(110,5);
INSERT INTO PAZNIC VALUES(111,6);
insert into paznic values(14,3);

ROLLBACK;
SELECT * FROM PAZNIC;

CREATE TABLE ANGAJAT_CURATENIE (ID_SALARIAT NUMBER(10) REFERENCES ANGAJAT(ID_SALARIAT),
ID_SEDIU NUMBER(10) REFERENCES SEDIU(ID_SEDIU));

INSERT INTO ANGAJAT_CURATENIE VALUES(103,1);
INSERT INTO ANGAJAT_CURATENIE VALUES (104,2);
INSERT INTO ANGAJAT_CURATENIE VALUES (112,1);
INSERT INTO ANGAJAT_CURATENIE VALUES (113,3);
INSERT INTO ANGAJAT_CURATENIE VALUES (116,6);
INSERT INTO ANGAJAT_CURATENIE VALUES (115,5);
INSERT INTO ANGAJAT_CURATENIE VALUES (114,4);


SELECT * FROM ANGAJAT_CURATENIE;


CREATE TABLE ORA_DE_CURS
(ID_ORA NUMBER(10) PRIMARY KEY, DATA DATE, ORA_INCEPUT VARCHAR(20), 
DURATA NUMBER(10), ID_STIL NUMBER(10) REFERENCES STIL_DE_DANS(ID_STIL),
ID_SALARIAT NUMBER(10) REFERENCES ANGAJAT(ID_SALARIAT));
 
INSERT INTO ORA_DE_CURS VALUES
(GENERATOR.NEXTVAL, SYSDATE ,'18:00',90,1,6063);

INSERT INTO ORA_DE_CURS VALUES
(GENERATOR.NEXTVAL, SYSDATE ,'20:00',90,1,6063);

INSERT INTO ORA_DE_CURS VALUES
(GENERATOR.NEXTVAL, SYSDATE ,'18:00',90,2,5760);

INSERT INTO ORA_DE_CURS VALUES
(GENERATOR.NEXTVAL, SYSDATE ,'18:00',90,3,5457);

INSERT INTO ORA_DE_CURS VALUES
(GENERATOR.NEXTVAL, SYSDATE ,'18:00',90,4,6366);

INSERT INTO ORA_DE_CURS VALUES
(GENERATOR.NEXTVAL, SYSDATE ,'20:00',90,4,6366);

INSERT INTO ORA_DE_CURS VALUES
(GENERATOR.NEXTVAL, SYSDATE ,'18:00',90,4,105);

INSERT INTO ORA_DE_CURS VALUES
(GENERATOR.NEXTVAL, SYSDATE ,'19:45',90,4,105);

INSERT INTO ORA_DE_CURS VALUES
(GENERATOR.NEXTVAL, SYSDATE ,'17:00',90,6,106);

INSERT INTO ORA_DE_CURS VALUES
(GENERATOR.NEXTVAL, SYSDATE ,'18:45',90,4,106);

INSERT INTO ORA_DE_CURS VALUES
(GENERATOR.NEXTVAL, SYSDATE ,'20:30',90,4,106);

INSERT INTO ORA_DE_CURS VALUES
(GENERATOR.NEXTVAL, SYSDATE ,'21:00',90,5,6063);

SELECT * FROM ORA_DE_CURS;

COMMIT;

--EX1 denumirea stilului de dans predat la ora 18:00 in data de 19.06.2022 si instructorul care il preda

select * from stil_De_dans;

select s.denumire, i.id_salariat,o.data from stil_de_dans s, ora_de_curs o,instructor i 
where s.id_stil=o.id_stil and o.id_stil=i.id_stil and o.ora_inceput='18:00' and TRUNC(o.data)=to_date('19-JUN-2022', 'dd-mm-YYYY');

--EX2 --cel mai scump abonament

select c.nume, c.prenume, a.tip from cursant c, abonament a
where a.pret=(select max(pret) from abonament);

--ex3 mare>=7 mediu>=4 mic<=3
SELECT ID_SEDIU,
CASE
    WHEN NR_SALI>=7 THEN 'MARE'
    WHEN NR_SALI<=7 AND NR_SALI>=4 THEN 'MEDIU'
    ELSE 'MIC'
END AS CATEGORIE
FROM SEDIU;   

select p.id_sediu from paznic p, sediu s where p.id_sediu=(select id_sediu from sediu where nr_sali=(select min(nr_sali)from sediu));
select id_sediu from sediu where nr_sali=(select min(nr_sali) from sediu);
select * from paznic;
--12
--stergem paznicul din sediul cu cele mai putine sali 
delete from paznic p
where p.id_sediu=(select id_sediu from sediu where nr_sali=(select min(nr_sali)from sediu));

select * from adresa;
select * from sala;

select id_sala from clasa where id_clasa= (select max(id_clasa) from clasa);
select max(id_sediu)from sediu;
select min(id_sala) from sala where id_sediu=(select min(id_sediu)from sediu);
--update
--clasa cu cel mai mare id intr o sala din alt sediu
update clasa set 
id_sala=(select min(id_sala) from sala where id_sediu=(select min(id_sediu)from sediu))
where id_clasa=(select max(id_clasa)from clasa);

--stergem un sediu aflat la o adresa din sectorul 3
delete from adresa s
where s.sector=(select max(sector) from adresa);

--media incasarilor si lunile in ordine alfabetica
with minc as (select luna, sum(suma) as thing
from incasari group by luna order by sum(suma) asc)
select * from minc;

--decode stilul de dans predat de instructor
select id_salariat,
decode(id_stil,1,'DANCEHALL',
            2,'HIP HOP',
            3,'LOCKING',
            4,'HOUSE',
            5,'WAACKING',
            6,'VOGUE',
            NULL) STIL_PREDAT
FROM INSTRUCTOR;


select *from eveniment;
--to_char si nvl
--sa se afiseze pentru cursantii care nu au email mesajul 'nu are email'
select id_cursant, NVL(TO_CHAR(email),'NU are email') from cursant;

--sa se afiseze evenimentele care ofera un numar de puncte pentru locul 3 care incepe cu cifra 1
select to_Char(nrpuncte3) from eveniment
where to_Char(nrpuncte3) like '1%';

--14 vizualizare compusa
Create view vizualizare (id_cursant, nume, prenume, data_nasterii,id_clasa,id_stil,id_sala)
as select c.id_cursant, c.nume, c.prenume, c.data_nasterii, c.id_clasa, cl.id_stil, cl.id_sala
from cursant c, clasa cl where c.id_clasa=cl.id_clasa ;

select * from vizualizare;
drop view vizualizare;

insert into vizualizare values (23,'ana','maria',sysdate,555,10,20);
rollback;


--16
--se vor afisa salile in care se desfasoare ore de curs, precum si clasele participante
--cursantii din clase
--sediile unde se afla salile
select c.id_cursant,cl.id_Clasa,s.id_sala,se.id_sediu
from (((cursant c full outer join clasa cl on c.id_clasa=cl.id_clasa) full outer join sala s on s.id_sala=cl.id_sala) 
full outer join sediu se on s.id_sediu=se.id_sediu)
order by c.id_clasa;

--division
--sa se afiseze numele cursantilor care se afla in clasa 20
select nume, prenume from cursant where id_clasa in (select id_clasa from clasa where id_clasa=20)
group by nume,prenume
having count(id_clasa)=(select count(*) from clasa where id_clasa=20);

--sa se afiseze id ul evenimentelor care s-au desfasurat in sediul cu id ul 2
select distinct id_eveniment from eveniment 
where not exists(select 1 from sediu s where s.id_sediu=6 and not exists (select 'x' from eveniment e where e.id_sediu=s.id_sediu));

--cerere neoptimizata
select o.* from ora_de_curs o, stil_de_dans s
where lower(s.denumire)='dancehall' and o.id_stil=s.id_stil;

select * from cursant;
select * from eveniment;

